name: apidocs
on:
    workflow_dispatch:

concurrency:
    group: "apidocs"
    cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
          contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install requirements for documentation generation
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pydoctor

    - name: Generate API documentation with pydoctor
      run: |

        # Run pydoctor build
        pydoctor \
            --project-name=PieZense \
            --project-url=https://github.com/$GITHUB_REPOSITORY \
            --html-viewsource-base=https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA \
            --html-base-url=https://$GITHUB_REPOSITORY_OWNER.github.io/${GITHUB_REPOSITORY#*/} \
            --html-output=./apidocs \
            --docformat=restructuredtext \
            --intersphinx=https://docs.python.org/3/objects.inv \
            ./piezense

    - name: Push API documentation to Github Pages (if on main branch)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        commit_message: "Generate API documentation"